name: "PHPStan"

on: [push, pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [7.2, 7.3, 7.4, 8.0, 8.1, 8.2]

            fail-fast: false

        name: PHP ${{matrix.php}}

        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - run: make phpstan
